set SESSION_NAME=A Name
set CHANNEL_ID=1234567890
set PROXY_ID=proxy_1
set DISCORD_TOKEN=abcd:123456789
set ENABLE_SHOW_ID=True
set HUMAN_PLAY=False
set ENABLE_AUTO_BUY_BALLS=True
set ENABLE_AUTO_RELEASE_DUPLICATES=True
set ENABLE_AUTO_EGG_HATCH=True
set ENABLE_AUTO_LOOTBOX_OPEN=True
set ENABLE_AUTO_QUEST_REROLL=True
set ENABLE_FISHING=True
set ENABLE_BATTLE_NPC=False
set ENABLE_HUNTING=True
set ENABLE_EXPLORING=True
set ENABLE_WEBHOOK=True
set ENABLE_AUTO_GRAZZ=True
set ENABLE_AUTO_REPEL=True
set ENABLE_AUTO_DAILY=True
set ENABLE_AUTO_CATCHBOT=True
set ENABLE_AUTO_SWAP=True
set ENABLE_AUTO_HUNT=True
"Pokemeow Autoplay.exe"
pause
