@echo off
cd /d %~dp0

set SESSION_NAME=Andrew
set CHANNEL_ID=1467588209054581054
set PROXY_ID=proxy_1
set DISCORD_TOKEN=PUT_YOUR_DISCORD_TOKEN_HERE

set ENABLE_SHOW_ID=True
set ENABLE_AUTO_BUY_BALLS=True
set ENABLE_AUTO_RELEASE_DUPLICATES=True
set ENABLE_AUTO_EGG_HATCH=True
set ENABLE_AUTO_LOOTBOX_OPEN=True
set ENABLE_AUTO_QUEST_REROLL=True
set ENABLE_FISHING=True
set ENABLE_BATTLE_NPC=True
set ENABLE_HUNTING=True
set ENABLE_EXPLORING=False
set ENABLE_WEBHOOK=True
set ENABLE_AUTO_GRAZZ=True
set ENABLE_AUTO_REPEL=True
set ENABLE_AUTO_DAILY=True
set ENABLE_AUTO_CATCHBOT=True
set ENABLE_AUTO_SWAP=True
set ENABLE_AUTO_HUNT=True

"Pokemeow Autoplay.exe"

pause
